Update backup script
Update backup script:
 * add verbose mode
 * cleanup backup dir before starting backup
 * add AWS ECR login in case it is needed to start containers

diff --git a/docker_deploy/roles/combine_backup/templates/combine-backup.j2 b/docker_deploy/roles/combine_backup/templates/combine-backup.j2
--- a/docker_deploy/roles/combine_backup/templates/combine-backup.j2
+++ b/docker_deploy/roles/combine_backup/templates/combine-backup.j2
@@ -6,44 +6,95 @@
 
 set -e
 
-# 1. Setup some useful environment variables
-DATE_STR=`date +%Y-%m-%d-%T`
-COMBINE_HOST={{ ansible_hostname }}
-BACKUP_FILE="combine-backup-${DATE_STR}.tar.gz"
-AWS_FILE="s3://thecombine.app/backups/${COMBINE_HOST}-${DATE_STR}.tar.gz"
-COMBINE_HOME=${COMBINE_HOME:="{{ combine_app_dir }}"}
+VERBOSE="0"
+
+echo_verbose() {
+  if [ "${VERBOSE}" == "1" ] ; then
+    echo $@
+  fi
+}
+
+usage() {
+  cat <<USAGE
+  Usage: $0 [-h] [-v]
+     Creates a backup of the combine database and backend containers
+  Options:
+     -h: help - print this message
+     -v: verbose - print progress of backup
+USAGE
+}
+
+while [[ $# -gt 0 ]] ; do
+  arg="$1"
+
+  case ${arg} in
+    -h|--help)
+      usage
+      exit 0
+      ;;
+    -v|--verbose)
+      VERBOSE="1"
+      ;;
+    -?)
+      echo "Invalid option: ${arg}."
+      usage
+      exit 2
+      ;;
+    *)
+      echo "Unrecognized argument: ${arg}"
+      usage
+      exit 1
+      ;;
+  esac
+  shift
+done
+
+echo_verbose "1. Setup some useful environment variables"
+DATE_STR=`date +%Y-%m-%d-%H-%M-%S`
+COMBINE_HOST="{{ combine_server_name | replace('.', '-') }}"
+BACKUP_FILE="combine-backup.tar.gz"
+AWS_FILE="s3://{{ aws_s3_backup_loc }}/${COMBINE_HOST}-${DATE_STR}.tar.gz"
+COMBINE_APP_DIR=${COMBINE_APP_DIR:="{{ combine_app_dir }}"}
 BACKUP_DIR=${BACKUP_DIR:="{{ combine_backup_dir }}"}
 
-cd ${COMBINE_HOME}
+cd ${COMBINE_APP_DIR}
 
-# 2. Create the backup directory
+echo_verbose "2. Prepare the backup directory"
 if [ ! -e "${BACKUP_DIR}" ] ; then
   mkdir -p ${BACKUP_DIR}
+else
+  for item in ${BACKUP_DIR}/dump ${BACKUP_DIR}/.CombineFiles ${BACKUP_DIR}/${BACKUP_FILE}
+  do
+    if [ -e "${item}" ] ; then
+      rm -rf ${item}
+    fi
+  done
 fi
 
-# 3. Stop the current containers
+echo_verbose "3. Stop the current containers"
 docker-compose down
 
-# 4. Start up just the backend and the database
+echo_verbose "4. Start up just the backend and the database"
+aws ecr get-login-password --profile {{ aws_ecr_profile }} | docker login --username AWS --password-stdin {{ aws_ecr }}
 docker-compose up --detach database backend
 
-# 5. Remove old backups
-rm -rf /var/backups/dump var/backups/.CombineFiles
 
-# 6. Dump the database
+echo_verbose "5. Dump the database"
 docker-compose exec database mongodump --db CombineDatabase --gzip --quiet
 DB_CONTAINER=`docker ps | grep database | sed "s/.* \([^ ][^ ]*\)$/\1/"`
 docker cp ${DB_CONTAINER}:dump/ ${BACKUP_DIR}
 
-# 7. Copy the backend files (commands are run relative the 'app' user's home directory)
+echo_verbose "6. Copy the backend files (commands are run relative the 'app' user's home directory)"
 BE_CONTAINER=`docker ps | grep backend | sed "s/.* \([^ ][^ ]*\)$/\1/"`
-docker cp ${BE_CONTAINER}:.CombineFiles/ ${BACKUP_DIR}
+docker cp ${BE_CONTAINER}:/home/app/.CombineFiles/ ${BACKUP_DIR}
 
-# 8. create the tarball for the backup
-tar --create --file=/var/backups/${BACKUP_FILE} --gzip --verbose .CombineFiles dump
-
-# 9. Remove old backups
+echo_verbose "7. create the tarball for the backup"
 cd ${BACKUP_DIR}
+tar --create --file=${BACKUP_FILE} --gzip --verbose .CombineFiles dump
+
+echo_verbose "8. Remove old backup files"
+# Running in ${BACKUP_DIR}
+rm -rf .CombineFiles dump
 ALL_BACKUPS=(`ls combine-backup*.tar.gz`)
 
 for bu in "${ALL_BACKUPS[@]}"; do
@@ -53,9 +104,14 @@ for bu in "${ALL_BACKUPS[@]}"; do
   fi
 done
 
-# 9. if aws-cli is installed, push backup to AWS S3 storage
+echo_verbose "9. if aws-cli is installed, push backup to AWS S3 storage"
 #    need to specify full path because $PATH does not contain
 #    /usr/local/bin when run as a cron job
-if [ -e /usr/local/bin/aws ] ; then
+if [ -x /usr/local/bin/aws ] ; then
   /usr/local/bin/aws s3 cp ${BACKUP_FILE} ${AWS_FILE} --profile {{ aws_backup_profile }}
 fi
+
+echo_verbose "10. Restart the containers"
+cd ${COMBINE_APP_DIR}
+docker-compose down
+docker-compose up --detach
